import type { Architecture } from '@/lib/types';
import { architecture, buildSystem, inDays, standardFunction } from './build';

/**
 * A social enterprise mapped service-first: what we deliver, then what runs it.
 *
 * Bigger than Riverside and messier in a different way — it has grown by
 * project, so two teams bought their own project tracker and a contract
 * inherited from a merger is still being paid for. It also shows what the
 * service-first path produces, which the other examples do not.
 */
export function buildGreenFutures(): Architecture {
  return architecture({
    organisation: {
      id: 'org-green',
      name: 'Green Futures CIC',
      type: 'social_enterprise',
      size: 'medium',
      staffCount: 38,
      createdAt: '',
      updatedAt: '',
    },

    functions: [
      standardFunction('finance', 'Finance', 'Accounts, payroll and contract billing'),
      standardFunction('governance', 'Governance', 'Board, policies and social impact reporting'),
      standardFunction('people', 'People', 'Staff, freelancers and training'),
      standardFunction('fundraising', 'Fundraising', 'Grants and earned income'),
      standardFunction('communications', 'Communications', 'Marketing and campaigns'),
      standardFunction('service_delivery', 'Service Delivery', 'Training, retrofit and garden projects'),
      standardFunction('operations', 'Operations', 'Vehicles, sites and scheduling'),
      standardFunction('data_reporting', 'Data & Reporting', 'Impact data and funder evidence'),
    ],

    services: [
      {
        id: 'svc-retrofit',
        name: 'Home retrofit advice',
        description: 'Home visits and energy efficiency plans',
        beneficiaries: 'Households in fuel poverty',
        status: 'active',
        functionIds: ['fn-service_delivery', 'fn-data_reporting'],
        systemIds: ['sys-dynamics', 'sys-airtable', 'sys-teams'],
      },
      {
        id: 'svc-training',
        name: 'Green skills training',
        description: 'Accredited courses for people entering the sector',
        beneficiaries: 'Adults changing career',
        status: 'active',
        functionIds: ['fn-service_delivery', 'fn-people'],
        systemIds: ['sys-dynamics', 'sys-eventbrite', 'sys-teams'],
      },
      {
        id: 'svc-gardens',
        name: 'Community gardens',
        description: 'Volunteer-run growing spaces on three sites',
        beneficiaries: 'Local residents and volunteers',
        status: 'active',
        functionIds: ['fn-service_delivery', 'fn-operations'],
        systemIds: ['sys-trello', 'sys-whatsapp'],
      },
      {
        id: 'svc-consultancy',
        name: 'Consultancy',
        description: 'Paid advisory work for housing associations',
        beneficiaries: 'Housing providers',
        status: 'planned',
        functionIds: ['fn-fundraising', 'fn-service_delivery'],
        systemIds: ['sys-dynamics'],
      },
    ],

    systems: [
      buildSystem({
        id: 'sys-dynamics',
        name: 'Microsoft Dynamics 365',
        type: 'crm',
        functions: ['fn-service_delivery', 'fn-fundraising', 'fn-data_reporting'],
        services: ['svc-retrofit', 'svc-training', 'svc-consultancy'],
        owner: 'own-ade',
        importance: 10,
        annualCost: 9600,
        seats: 30,
        renewalDate: inDays(95),
        noticePeriodDays: 60,
        notes: 'Holds every household record. Migrating away would take a year.',
      }),
      buildSystem({
        id: 'sys-m365',
        name: 'Microsoft 365',
        type: 'document_management',
        functions: ['fn-governance', 'fn-operations', 'fn-people'],
        owner: 'own-ade',
        importance: 10,
        annualCost: 4560,
        seats: 38,
      }),
      buildSystem({
        id: 'sys-teams',
        name: 'Microsoft Teams',
        type: 'messaging',
        functions: ['fn-operations', 'fn-people'],
        services: ['svc-retrofit', 'svc-training'],
        owner: 'own-ade',
        importance: 9,
        annualCost: 0,
        notes: 'Included with Microsoft 365',
      }),
      buildSystem({
        id: 'sys-sage',
        name: 'Sage',
        type: 'finance',
        functions: ['fn-finance'],
        owner: 'own-ruth',
        importance: 10,
        annualCost: 2400,
        renewalDate: inDays(14),
        noticePeriodDays: 90,
        notes: 'Notice period already passed for this year. Locked in until next renewal.',
      }),
      buildSystem({
        id: 'sys-trello',
        name: 'Trello',
        type: 'database',
        functions: ['fn-operations', 'fn-service_delivery'],
        services: ['svc-gardens'],
        owner: 'own-lena',
        importance: 5,
        annualCost: 500,
        notes: 'Gardens team runs everything here.',
      }),
      buildSystem({
        id: 'sys-asana',
        name: 'Asana',
        type: 'database',
        functions: ['fn-operations'],
        owner: 'own-ade',
        importance: 5,
        annualCost: 1440,
        notes: 'Retrofit team chose this. Same job as Trello, twice the price.',
      }),
      buildSystem({
        id: 'sys-airtable',
        name: 'Airtable',
        type: 'database',
        functions: ['fn-data_reporting'],
        services: ['svc-retrofit'],
        owner: 'own-lena',
        importance: 7,
        annualCost: 960,
      }),
      buildSystem({
        id: 'sys-powerbi',
        name: 'Power BI',
        type: 'database',
        functions: ['fn-data_reporting', 'fn-governance'],
        owner: 'own-lena',
        importance: 6,
        annualCost: 1200,
      }),
      buildSystem({
        id: 'sys-breathehr',
        name: 'BreatheHR',
        type: 'hr',
        functions: ['fn-people'],
        owner: 'own-ruth',
        importance: 8,
        annualCost: 1560,
        seats: 38,
      }),
      buildSystem({
        id: 'sys-eventbrite',
        name: 'Eventbrite',
        type: 'other',
        functions: ['fn-service_delivery', 'fn-communications'],
        services: ['svc-training'],
        owner: 'own-nadia',
        importance: 6,
        annualCost: 780,
      }),
      buildSystem({
        id: 'sys-mailchimp',
        name: 'Mailchimp',
        type: 'email',
        functions: ['fn-communications'],
        owner: 'own-nadia',
        importance: 6,
        annualCost: 900,
      }),
      buildSystem({
        id: 'sys-squarespace',
        name: 'Squarespace',
        type: 'website',
        functions: ['fn-communications'],
        owner: 'own-nadia',
        importance: 7,
        annualCost: 216,
      }),
      buildSystem({
        id: 'sys-whatsapp',
        name: 'WhatsApp',
        type: 'messaging',
        functions: ['fn-operations', 'fn-service_delivery'],
        services: ['svc-gardens'],
        owner: 'own-lena',
        importance: 6,
        annualCost: 0,
        isShadow: true,
        notes: 'Volunteer coordination happens here, on personal phones. Nobody agreed to it.',
      }),
      buildSystem({
        id: 'sys-legacy-crm',
        name: 'Charitylog',
        type: 'case_management',
        functions: ['fn-service_delivery'],
        status: 'retiring',
        owner: 'own-ade',
        importance: 3,
        annualCost: 1100,
        renewalDate: inDays(240),
        noticePeriodDays: 30,
        notes: 'Came with the merger. Read-only now, but still being paid for.',
      }),
      buildSystem({
        id: 'sys-fleet',
        name: 'Fleet tracker',
        type: 'other',
        functions: ['fn-operations'],
        owner: 'own-ruth',
        importance: 4,
        notes: 'Vans and minibus. Nobody can find the contract.',
      }),
    ],

    dataCategories: [
      {
        id: 'dc-households',
        name: 'Household records',
        sensitivity: 'restricted',
        containsPersonalData: true,
        systemIds: ['sys-dynamics', 'sys-airtable', 'sys-legacy-crm'],
        subjects: 'Households we visit',
        lawfulBasis: 'public_task',
        retention: '7 years, to match the funding contract',
      },
      {
        id: 'dc-learners',
        name: 'Learner records',
        sensitivity: 'confidential',
        containsPersonalData: true,
        systemIds: ['sys-dynamics', 'sys-eventbrite'],
        subjects: 'People on our courses',
        lawfulBasis: 'contract',
      },
      {
        id: 'dc-volunteers',
        name: 'Volunteer contacts',
        sensitivity: 'confidential',
        containsPersonalData: true,
        systemIds: ['sys-whatsapp', 'sys-trello'],
        subjects: 'Garden volunteers',
      },
      {
        id: 'dc-staff',
        name: 'Staff records',
        sensitivity: 'restricted',
        containsPersonalData: true,
        systemIds: ['sys-breathehr', 'sys-sage'],
        subjects: 'Employees and freelancers',
        lawfulBasis: 'contract',
        retention: '6 years after leaving',
      },
      {
        id: 'dc-impact',
        name: 'Impact measurements',
        sensitivity: 'internal',
        containsPersonalData: false,
        systemIds: ['sys-powerbi', 'sys-airtable'],
      },
    ],

    integrations: [
      {
        id: 'int-dyn-powerbi',
        sourceSystemId: 'sys-dynamics',
        targetSystemId: 'sys-powerbi',
        type: 'api',
        direction: 'one_way',
        frequency: 'scheduled',
        reliability: 'reliable',
      },
      {
        id: 'int-eventbrite-dyn',
        sourceSystemId: 'sys-eventbrite',
        targetSystemId: 'sys-dynamics',
        type: 'file_transfer',
        direction: 'one_way',
        frequency: 'on_demand',
        reliability: 'fragile',
        description: 'Course bookings exported and re-imported by hand each month',
      },
      {
        id: 'int-airtable-powerbi',
        sourceSystemId: 'sys-airtable',
        targetSystemId: 'sys-powerbi',
        type: 'api',
        direction: 'one_way',
        frequency: 'scheduled',
        reliability: 'reliable',
      },
      {
        id: 'int-sage-m365',
        sourceSystemId: 'sys-sage',
        targetSystemId: 'sys-m365',
        type: 'manual',
        direction: 'one_way',
        frequency: 'scheduled',
        reliability: 'fragile',
        description: 'Month-end reports saved to SharePoint by hand',
      },
    ],

    owners: [
      { id: 'own-ade', name: 'Ade Fashola', role: 'Head of Delivery', isExternal: false },
      { id: 'own-ruth', name: 'Ruth Kelleher', role: 'Finance & HR', isExternal: false },
      { id: 'own-lena', name: 'Lena Petrova', role: 'Impact Lead', isExternal: false },
      { id: 'own-nadia', name: 'Nadia Rahman', role: 'Communications', isExternal: false },
      { id: 'own-it', name: 'Bluepoint IT', role: 'Outsourced IT support', isExternal: true },
    ],

    externalParties: [
      { id: 'party-ukgov', name: 'Department for Energy Security', type: 'funder', location: 'uk' },
      { id: 'party-housing', name: 'Meadowvale Housing Association', type: 'partner', location: 'uk' },
      { id: 'party-awarding', name: 'City & Guilds', type: 'regulator', location: 'uk' },
      { id: 'party-auditor', name: 'Hartley & Coe', type: 'auditor', location: 'uk' },
      { id: 'party-eu-survey', name: 'Enquête EU', type: 'supplier', location: 'eea' },
    ],

    dataFlows: [
      {
        id: 'flow-energy',
        systemId: 'sys-dynamics',
        partyId: 'party-ukgov',
        dataCategoryIds: ['dc-households'],
        purpose: 'Quarterly grant claim evidence',
        method: 'portal',
        frequency: 'scheduled',
      },
      {
        id: 'flow-housing',
        systemId: 'sys-dynamics',
        partyId: 'party-housing',
        dataCategoryIds: ['dc-households'],
        purpose: 'Referrals back to the landlord',
        method: 'email',
        frequency: 'on_demand',
      },
      {
        id: 'flow-awarding',
        systemId: 'sys-dynamics',
        partyId: 'party-awarding',
        dataCategoryIds: ['dc-learners'],
        purpose: 'Registering learners for accreditation',
        method: 'portal',
        frequency: 'scheduled',
      },
      {
        id: 'flow-auditor',
        systemId: 'sys-sage',
        partyId: 'party-auditor',
        dataCategoryIds: ['dc-staff'],
        purpose: 'Annual audit',
        method: 'file_transfer',
        frequency: 'annual',
      },
      {
        id: 'flow-survey',
        systemId: 'sys-dynamics',
        partyId: 'party-eu-survey',
        dataCategoryIds: ['dc-learners'],
        purpose: 'Independent course satisfaction survey',
        method: 'api',
        frequency: 'scheduled',
      },
    ],

    metadata: { mappingPath: 'service_first' },
  });
}
