import type { Architecture } from '@/lib/types';
import { architecture, buildSystem, customFunction, inDays, standardFunction } from './build';

/**
 * A district council's back office, using the sector function set.
 *
 * The shape is different from a charity: statutory services, contracts with
 * years left on them, systems nobody chose that cannot simply be swapped, and
 * an on-premise estate that has outlived the people who installed it. It is
 * here because local government reorganisation is one of the cases Stackmap
 * is meant to help with, and a charity example does not rehearse it.
 */
export function buildNorthfieldCouncil(): Architecture {
  return architecture({
    organisation: {
      id: 'org-northfield',
      name: 'Northfield Borough Council',
      type: 'council',
      size: 'large',
      staffCount: 420,
      createdAt: '',
      updatedAt: '',
    },

    functions: [
      standardFunction('finance', 'Finance', 'Corporate finance, treasury and procurement'),
      standardFunction('governance', 'Governance', 'Committees, decisions and information governance'),
      standardFunction('people', 'People', 'HR, payroll and workforce planning'),
      standardFunction('data_reporting', 'Data & Reporting', 'Performance, statutory returns and open data'),
      customFunction('fn-revs', 'Revenues & Benefits', 'Council tax, business rates and housing benefit'),
      customFunction('fn-planning', 'Planning & Building Control', 'Applications, enforcement and land charges'),
      customFunction('fn-waste', 'Waste & Environment', 'Collections, street scene and licensing'),
      customFunction('fn-customer', 'Customer Services', 'Contact centre, web forms and complaints'),
    ],

    systems: [
      buildSystem({
        id: 'sys-revs',
        name: 'Northgate Revenues & Benefits',
        type: 'other',
        functions: ['fn-revs', 'fn-finance'],
        hosting: 'on_premise',
        owner: 'own-david',
        importance: 10,
        annualCost: 84000,
        renewalDate: inDays(300),
        noticePeriodDays: 180,
        notes: 'Statutory. Billing stops without it. Replacement is a two-year programme.',
      }),
      buildSystem({
        id: 'sys-uniform',
        name: 'Idox Uniform',
        type: 'case_management',
        functions: ['fn-planning'],
        hosting: 'hybrid',
        owner: 'own-david',
        importance: 9,
        annualCost: 46000,
        renewalDate: inDays(60),
        noticePeriodDays: 90,
        notes: 'Planning register and enforcement. Notice window has already closed.',
      }),
      buildSystem({
        id: 'sys-bartec',
        name: 'Bartec Collective',
        type: 'other',
        functions: ['fn-waste'],
        owner: 'own-yusuf',
        importance: 9,
        annualCost: 31000,
        notes: 'In-cab devices on every round. Missed-bin reporting depends on it.',
      }),
      buildSystem({
        id: 'sys-granicus',
        name: 'Granicus',
        type: 'website',
        functions: ['fn-customer', 'fn-governance'],
        owner: 'own-yusuf',
        importance: 8,
        annualCost: 27000,
      }),
      buildSystem({
        id: 'sys-modern-gov',
        name: 'Modern.gov',
        type: 'document_management',
        functions: ['fn-governance'],
        owner: 'own-claire',
        importance: 7,
        annualCost: 9500,
      }),
      buildSystem({
        id: 'sys-m365',
        name: 'Microsoft 365',
        type: 'document_management',
        functions: ['fn-governance', 'fn-people', 'fn-customer'],
        owner: 'own-david',
        importance: 10,
        annualCost: 92000,
        seats: 420,
      }),
      buildSystem({
        id: 'sys-itrent',
        name: 'iTrent',
        type: 'hr',
        functions: ['fn-people', 'fn-finance'],
        hosting: 'hybrid',
        owner: 'own-claire',
        importance: 10,
        annualCost: 38000,
        renewalDate: inDays(150),
        noticePeriodDays: 120,
      }),
      buildSystem({
        id: 'sys-unit4',
        name: 'Unit4',
        type: 'finance',
        functions: ['fn-finance'],
        hosting: 'hybrid',
        owner: 'own-claire',
        importance: 10,
        annualCost: 64000,
      }),
      buildSystem({
        id: 'sys-arcgis',
        name: 'ArcGIS Online',
        type: 'database',
        functions: ['fn-planning', 'fn-waste', 'fn-data_reporting'],
        owner: 'own-yusuf',
        importance: 8,
        annualCost: 22000,
      }),
      buildSystem({
        id: 'sys-powerbi',
        name: 'Power BI',
        type: 'database',
        functions: ['fn-data_reporting'],
        owner: 'own-priti',
        importance: 7,
        annualCost: 14000,
      }),
      buildSystem({
        id: 'sys-crm',
        name: 'Microsoft Dynamics 365',
        type: 'crm',
        functions: ['fn-customer'],
        owner: 'own-yusuf',
        importance: 9,
        annualCost: 41000,
        notes: 'Contact centre case handling. Integrations to the back office are partial.',
      }),
      buildSystem({
        id: 'sys-landcharges',
        name: 'Local land charges register',
        type: 'database',
        functions: ['fn-planning'],
        hosting: 'on_premise',
        status: 'legacy',
        owner: 'own-david',
        importance: 6,
        annualCost: 4200,
        notes: 'Access database on a server in the basement. One officer knows how it works.',
      }),
      buildSystem({
        id: 'sys-licensing',
        name: 'Licensing spreadsheets',
        type: 'spreadsheet',
        functions: ['fn-waste'],
        owner: 'own-yusuf',
        importance: 5,
        annualCost: 0,
        isShadow: true,
        notes: 'Taxi and premises licences tracked in Excel on a shared drive.',
      }),
      buildSystem({
        id: 'sys-govnotify',
        name: 'GOV.UK Notify',
        type: 'email',
        functions: ['fn-customer', 'fn-revs'],
        owner: 'own-priti',
        importance: 7,
        annualCost: 0,
        notes: 'Free for public sector. Texts and emails for appointments and reminders.',
      }),
    ],

    dataCategories: [
      {
        id: 'dc-counciltax',
        name: 'Council tax and benefit records',
        sensitivity: 'restricted',
        containsPersonalData: true,
        systemIds: ['sys-revs', 'sys-crm'],
        subjects: 'Residents and businesses in the borough',
        lawfulBasis: 'legal_obligation',
        retention: '7 years after the account closes',
      },
      {
        id: 'dc-planning',
        name: 'Planning applications',
        sensitivity: 'public',
        containsPersonalData: true,
        systemIds: ['sys-uniform', 'sys-arcgis', 'sys-landcharges'],
        subjects: 'Applicants and objectors',
        lawfulBasis: 'public_task',
        retention: 'Permanent, as a statutory register',
      },
      {
        id: 'dc-waste',
        name: 'Collection and licensing records',
        sensitivity: 'internal',
        containsPersonalData: true,
        systemIds: ['sys-bartec', 'sys-licensing'],
        subjects: 'Householders and licence holders',
      },
      {
        id: 'dc-staff',
        name: 'Employee records',
        sensitivity: 'restricted',
        containsPersonalData: true,
        systemIds: ['sys-itrent', 'sys-unit4'],
        subjects: 'Council employees and members',
        lawfulBasis: 'contract',
        retention: '6 years after leaving',
      },
      {
        id: 'dc-performance',
        name: 'Performance data',
        sensitivity: 'internal',
        containsPersonalData: false,
        systemIds: ['sys-powerbi'],
      },
    ],

    integrations: [
      {
        id: 'int-revs-unit4',
        sourceSystemId: 'sys-revs',
        targetSystemId: 'sys-unit4',
        type: 'file_transfer',
        direction: 'one_way',
        frequency: 'scheduled',
        reliability: 'reliable',
        description: 'Nightly cash posting file',
      },
      {
        id: 'int-crm-revs',
        sourceSystemId: 'sys-crm',
        targetSystemId: 'sys-revs',
        type: 'api',
        direction: 'two_way',
        frequency: 'real_time',
        reliability: 'fragile',
        description: 'Account lookups from the contact centre. Times out at month end.',
      },
      {
        id: 'int-uniform-arcgis',
        sourceSystemId: 'sys-uniform',
        targetSystemId: 'sys-arcgis',
        type: 'database_link',
        direction: 'one_way',
        frequency: 'scheduled',
        reliability: 'reliable',
      },
      {
        id: 'int-bartec-crm',
        sourceSystemId: 'sys-bartec',
        targetSystemId: 'sys-crm',
        type: 'api',
        direction: 'one_way',
        frequency: 'real_time',
        reliability: 'reliable',
      },
      {
        id: 'int-itrent-unit4',
        sourceSystemId: 'sys-itrent',
        targetSystemId: 'sys-unit4',
        type: 'file_transfer',
        direction: 'one_way',
        frequency: 'scheduled',
        reliability: 'reliable',
      },
      {
        id: 'int-landcharges',
        sourceSystemId: 'sys-landcharges',
        targetSystemId: 'sys-uniform',
        type: 'manual',
        direction: 'one_way',
        frequency: 'on_demand',
        reliability: 'fragile',
        description: 'Re-keyed by hand. The only route off the old register.',
      },
    ],

    owners: [
      { id: 'own-david', name: 'David Nwosu', role: 'Head of ICT', isExternal: false },
      { id: 'own-claire', name: 'Claire Sutherland', role: 'Corporate Services', isExternal: false },
      { id: 'own-yusuf', name: 'Yusuf Demir', role: 'Customer & Environment', isExternal: false },
      { id: 'own-priti', name: 'Priti Nair', role: 'Data & Performance', isExternal: false },
    ],

    externalParties: [
      { id: 'party-dwp', name: 'Department for Work and Pensions', type: 'regulator', location: 'uk' },
      { id: 'party-valuation', name: 'Valuation Office Agency', type: 'regulator', location: 'uk' },
      { id: 'party-audit', name: 'Grant Thornton', type: 'auditor', location: 'uk' },
      { id: 'party-waste', name: 'Northfield Waste Services Ltd', type: 'supplier', location: 'uk' },
    ],

    dataFlows: [
      {
        id: 'flow-dwp',
        systemId: 'sys-revs',
        partyId: 'party-dwp',
        dataCategoryIds: ['dc-counciltax'],
        purpose: 'Housing benefit subsidy claims and data matching',
        method: 'file_transfer',
        frequency: 'scheduled',
      },
      {
        id: 'flow-voa',
        systemId: 'sys-revs',
        partyId: 'party-valuation',
        dataCategoryIds: ['dc-counciltax'],
        purpose: 'Property banding updates',
        method: 'api',
        frequency: 'scheduled',
      },
      {
        id: 'flow-audit',
        systemId: 'sys-unit4',
        partyId: 'party-audit',
        dataCategoryIds: ['dc-staff'],
        purpose: 'Annual external audit',
        method: 'portal',
        frequency: 'annual',
      },
      {
        id: 'flow-waste-contractor',
        systemId: 'sys-bartec',
        partyId: 'party-waste',
        dataCategoryIds: ['dc-waste'],
        purpose: 'Round schedules and missed collections',
        method: 'api',
        frequency: 'real_time',
      },
    ],

    services: [],
  });
}
