import type { Architecture } from '@/lib/types';
import { architecture, buildSystem, inDays, standardFunction } from './build';

/**
 * A small advice charity: the organisation Stackmap was built for.
 *
 * Deliberately imperfect. It has two CRMs nobody has reconciled, a contract
 * whose notice period has already run out, a spreadsheet holding case data
 * that no one signed off, and a data protection record that is half finished.
 * An example where everything is tidy would show the views working and teach
 * nothing about why they exist.
 */
export function buildRiversideAdvice(): Architecture {
  return architecture({
    organisation: {
      id: 'org-riverside',
      name: 'Riverside Advice',
      type: 'charity',
      size: 'small',
      staffCount: 9,
      createdAt: '',
      updatedAt: '',
    },

    functions: [
      standardFunction('finance', 'Finance', 'Bookkeeping, payroll and the annual return'),
      standardFunction('governance', 'Governance', 'Trustees, policies and regulatory filing'),
      standardFunction('people', 'People', 'Staff, volunteers and recruitment'),
      standardFunction('fundraising', 'Fundraising', 'Grants, donors and campaigns'),
      standardFunction('communications', 'Communications', 'Website, newsletter and social'),
      standardFunction('service_delivery', 'Service Delivery', 'Advice appointments and casework'),
      standardFunction('operations', 'Operations', 'Day-to-day running of the office'),
      standardFunction('data_reporting', 'Data & Reporting', 'Impact measurement and funder reports'),
    ],

    services: [
      {
        id: 'svc-debt',
        name: 'Debt advice drop-in',
        description: 'Weekly drop-in sessions at the community centre',
        beneficiaries: 'Residents in financial difficulty',
        status: 'active',
        functionIds: ['fn-service_delivery'],
        systemIds: ['sys-lamplight', 'sys-sheets'],
      },
      {
        id: 'svc-benefits',
        name: 'Benefits casework',
        description: 'Casework and tribunal representation',
        beneficiaries: 'People appealing benefit decisions',
        status: 'active',
        functionIds: ['fn-service_delivery'],
        systemIds: ['sys-lamplight'],
      },
    ],

    systems: [
      buildSystem({
        id: 'sys-lamplight',
        name: 'Lamplight',
        type: 'case_management',
        functions: ['fn-service_delivery', 'fn-data_reporting'],
        services: ['svc-debt', 'svc-benefits'],
        owner: 'own-priya',
        importance: 10,
        annualCost: 1800,
        seats: 9,
        // Notice ran out before anyone looked: the renewal view exists for this
        renewalDate: inDays(40),
        noticePeriodDays: 90,
        notes: 'Every case note lives here. Nothing else would do the job on Monday morning.',
      }),
      buildSystem({
        id: 'sys-xero',
        name: 'Xero',
        type: 'finance',
        functions: ['fn-finance'],
        owner: 'own-mark',
        importance: 9,
        annualCost: 360,
        seats: 2,
        renewalDate: inDays(180),
        noticePeriodDays: 30,
      }),
      buildSystem({
        id: 'sys-google',
        name: 'Google Workspace',
        type: 'document_management',
        functions: ['fn-governance', 'fn-operations'],
        owner: 'own-mark',
        importance: 9,
        annualCost: 648,
        seats: 9,
      }),
      buildSystem({
        id: 'sys-salesforce',
        name: 'Salesforce',
        type: 'crm',
        functions: ['fn-fundraising'],
        owner: 'own-jo',
        importance: 6,
        annualCost: 1200,
        notes: 'Set up by a former fundraiser. Only the grants pipeline is really used.',
      }),
      buildSystem({
        id: 'sys-donorfy',
        name: 'Donorfy',
        type: 'crm',
        functions: ['fn-fundraising'],
        owner: 'own-jo',
        importance: 5,
        annualCost: 720,
        notes: 'Bought for the Christmas appeal. Overlaps with Salesforce — nobody has decided.',
      }),
      buildSystem({
        id: 'sys-mailchimp',
        name: 'Mailchimp',
        type: 'email',
        functions: ['fn-communications', 'fn-fundraising'],
        owner: 'own-jo',
        importance: 6,
        annualCost: 300,
      }),
      buildSystem({
        id: 'sys-wordpress',
        name: 'WordPress',
        type: 'website',
        functions: ['fn-communications'],
        owner: 'own-jo',
        importance: 7,
        annualCost: 180,
        url: 'https://example.org',
      }),
      buildSystem({
        id: 'sys-slack',
        name: 'Slack',
        type: 'messaging',
        functions: ['fn-people', 'fn-operations'],
        owner: 'own-mark',
        importance: 7,
        annualCost: 0,
        notes: 'Free plan. History disappears after 90 days, which has bitten us once.',
      }),
      buildSystem({
        id: 'sys-breathehr',
        name: 'BreatheHR',
        type: 'hr',
        functions: ['fn-people'],
        owner: 'own-sam',
        importance: 6,
        annualCost: 480,
        renewalDate: inDays(21),
        noticePeriodDays: 30,
      }),
      buildSystem({
        id: 'sys-zoom',
        name: 'Zoom',
        type: 'messaging',
        functions: ['fn-service_delivery', 'fn-operations'],
        owner: 'own-sam',
        importance: 5,
        annualCost: 144,
      }),
      buildSystem({
        id: 'sys-canva',
        name: 'Canva',
        type: 'other',
        functions: ['fn-communications'],
        owner: 'own-jo',
        importance: 3,
        annualCost: 110,
      }),
      buildSystem({
        id: 'sys-gocardless',
        name: 'GoCardless',
        type: 'finance',
        functions: ['fn-fundraising', 'fn-finance'],
        owner: 'own-mark',
        importance: 7,
        annualCost: 240,
      }),
      buildSystem({
        id: 'sys-sheets',
        name: 'Google Sheets',
        type: 'spreadsheet',
        functions: ['fn-data_reporting', 'fn-service_delivery'],
        services: ['svc-debt'],
        owner: 'own-priya',
        importance: 8,
        annualCost: 0,
        isShadow: true,
        notes: 'The waiting list nobody meant to build. Holds client names and phone numbers.',
      }),
      buildSystem({
        id: 'sys-old-server',
        name: 'Office file server',
        type: 'document_management',
        functions: ['fn-operations'],
        hosting: 'on_premise',
        status: 'legacy',
        owner: 'own-mark',
        importance: 4,
        annualCost: 0,
        notes: 'Under the desk in the back office. Nobody is certain what is still on it.',
      }),
    ],

    dataCategories: [
      {
        id: 'dc-cases',
        name: 'Client case notes',
        sensitivity: 'restricted',
        containsPersonalData: true,
        systemIds: ['sys-lamplight', 'sys-sheets'],
        subjects: 'People we advise',
        lawfulBasis: 'legitimate_interests',
        retention: '6 years after the case closes',
      },
      {
        id: 'dc-donors',
        name: 'Donor records',
        sensitivity: 'confidential',
        containsPersonalData: true,
        systemIds: ['sys-salesforce', 'sys-donorfy', 'sys-mailchimp'],
        subjects: 'Donors and supporters',
        // Left unfinished on purpose: the record shows what it still needs
        lawfulBasis: 'consent',
      },
      {
        id: 'dc-staff',
        name: 'Staff records',
        sensitivity: 'restricted',
        containsPersonalData: true,
        systemIds: ['sys-breathehr'],
        subjects: 'Employees and volunteers',
        lawfulBasis: 'contract',
        retention: '6 years after leaving',
      },
      {
        id: 'dc-website',
        name: 'Website content',
        sensitivity: 'public',
        containsPersonalData: false,
        systemIds: ['sys-wordpress'],
      },
    ],

    integrations: [
      {
        id: 'int-gc-xero',
        sourceSystemId: 'sys-gocardless',
        targetSystemId: 'sys-xero',
        type: 'api',
        direction: 'one_way',
        frequency: 'scheduled',
        reliability: 'reliable',
        description: 'Direct debits post into the accounts nightly',
      },
      {
        id: 'int-sf-mc',
        sourceSystemId: 'sys-salesforce',
        targetSystemId: 'sys-mailchimp',
        type: 'api',
        direction: 'two_way',
        frequency: 'scheduled',
        reliability: 'reliable',
      },
      {
        id: 'int-lamplight-sheets',
        sourceSystemId: 'sys-lamplight',
        targetSystemId: 'sys-sheets',
        type: 'manual',
        direction: 'one_way',
        frequency: 'on_demand',
        reliability: 'fragile',
        description: 'Someone exports a CSV each quarter and pastes it in by hand',
      },
    ],

    owners: [
      { id: 'own-priya', name: 'Priya Shah', role: 'Advice Manager', isExternal: false },
      { id: 'own-mark', name: 'Mark Ellis', role: 'Operations Lead', isExternal: false },
      { id: 'own-jo', name: 'Jo Bennett', role: 'Fundraising & Comms', isExternal: false },
      { id: 'own-sam', name: 'Sam Okafor', role: 'Office Manager', isExternal: false },
    ],

    externalParties: [
      { id: 'party-lottery', name: 'The National Lottery Community Fund', type: 'funder', location: 'uk' },
      { id: 'party-council', name: 'Riverside Borough Council', type: 'partner', location: 'uk' },
      { id: 'party-analytics', name: 'Northbeam Analytics', type: 'supplier', location: 'rest_of_world' },
    ],

    dataFlows: [
      {
        id: 'flow-council',
        systemId: 'sys-lamplight',
        partyId: 'party-council',
        dataCategoryIds: ['dc-cases'],
        purpose: 'Quarterly contract reporting on advice sessions delivered',
        method: 'portal',
        frequency: 'scheduled',
      },
      {
        id: 'flow-lottery',
        systemId: 'sys-salesforce',
        partyId: 'party-lottery',
        dataCategoryIds: ['dc-donors'],
        purpose: 'Annual grant report',
        method: 'file_transfer',
        frequency: 'annual',
      },
      {
        id: 'flow-analytics',
        systemId: 'sys-wordpress',
        partyId: 'party-analytics',
        dataCategoryIds: ['dc-website'],
        purpose: 'Website visitor statistics',
        method: 'api',
        frequency: 'real_time',
      },
    ],
  });
}
